-- AlterTable
ALTER TABLE "Invoices" ALTER COLUMN "rate" SET DEFAULT 0.00,
ALTER COLUMN "rate" SET DATA TYPE DECIMAL(65,2),
ALTER COLUMN "quantity" SET DEFAULT 0.00,
ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(65,2),
ALTER COLUMN "lineTotal" SET DEFAULT 0.00,
ALTER COLUMN "lineTotal" SET DATA TYPE DECIMAL(65,2),
ALTER COLUMN "issuedDate" DROP NOT NULL,
ALTER COLUMN "totalOutstanding" DROP NOT NULL,
ALTER COLUMN "totalOutstanding" SET DEFAULT 0.00,
ALTER COLUMN "totalOutstanding" SET DATA TYPE DECIMAL(65,2);
